# Generated by Django 5.0.6 on 2024-06-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightalert',
            name='destination_city',
        ),
        migrations.AddField(
            model_name='flightalert',
            name='destination_cities',
            field=models.ManyToManyField(related_name='destination_cities', to='tracker.city'),
        ),
    ]
