# Generated by Django 5.0.6 on 2024-06-04 20:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_flightalert_destination_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightalert',
            name='end_date',
            field=models.DateField(default=datetime.date(2025, 12, 31)),
        ),
        migrations.AddField(
            model_name='flightalert',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20)),
                ('departure_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('departure_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_flights', to='tracker.city')),
                ('destination_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_flights', to='tracker.city')),
            ],
        ),
        migrations.AddField(
            model_name='flightalert',
            name='flights',
            field=models.ManyToManyField(related_name='flight_alerts', to='tracker.flight'),
        ),
    ]
