# Generated by Django 5.0.6 on 2024-06-04 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_flightalert_end_date_flightalert_start_date_flight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightalert',
            name='flights',
        ),
        migrations.RemoveField(
            model_name='flightalert',
            name='lowest_price',
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lowest_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('departure_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_routes', to='tracker.city')),
                ('destination_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_routes', to='tracker.city')),
            ],
        ),
        migrations.AddField(
            model_name='flightalert',
            name='routes',
            field=models.ManyToManyField(related_name='flight_alerts', to='tracker.route'),
        ),
        migrations.DeleteModel(
            name='Flight',
        ),
    ]
